MPG: float = 10.0
MAX_RANGE_MILES: float = 500.0
MAX_OFF_ROUTE_MILES: float = 5.0

TANK_CAPACITY_GALLONS: float = MAX_RANGE_MILES / MPG   # derived
FUEL_AT_DEPARTURE: float = TANK_CAPACITY_GALLONS        # always start full

MIN_TRIP_DISTANCE_MILES: float = 1.0

DEFAULT_BUFFER_GALLONS: float = 2.0
DEFAULT_GREEDY_FILL: bool = False
